FROM ubuntu  20.04

# Install Nginx
RUN apt-get -y update && apt-get -y install nginx

# Copy the Nginx index
COPY inxdex.html /var/www/html/index.html

# Expose the port for access
EXPOSE 80/tcp

# Run the Nginx server
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
